// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Takazono.Ojt.WebApi.Data;

#nullable disable

namespace Takazono.Ojt.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Takazono.Ojt.WebApi.Entities.Customer", b =>
                {
                    b.Property<long>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sid"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("contract_end_date");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("contract_start_date");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date_time");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_name");

                    b.Property<long?>("CreatedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("created_sid");

                    b.Property<byte>("CustomerRankKubun")
                        .HasColumnType("tinyint")
                        .HasColumnName("customer_rank_kubun");

                    b.Property<int>("DisplayOrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("display_order_number");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("modified_name");

                    b.Property<long?>("ModifiedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_sid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("postal_code");

                    b.Property<decimal?>("PreferentialDiscountRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("preferential_discount_rate");

                    b.Property<bool>("UseFlag")
                        .HasColumnType("bit")
                        .HasColumnName("use_flag");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Sid");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("m_customer", (string)null);
                });

            modelBuilder.Entity("Takazono.Ojt.WebApi.Entities.Store", b =>
                {
                    b.Property<long>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sid"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date_time");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_name");

                    b.Property<long?>("CreatedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("created_sid");

                    b.Property<int>("DisplayOrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("display_order_number");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("modified_name");

                    b.Property<long?>("ModifiedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_sid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("postal_code");

                    b.Property<bool>("UseFlag")
                        .HasColumnType("bit")
                        .HasColumnName("use_flag");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Sid");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("m_store", (string)null);
                });

            modelBuilder.Entity("Takazono.Ojt.WebApi.Entities.Supplier", b =>
                {
                    b.Property<long>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sid"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("code");

                    b.Property<string>("CorporateNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("corporate_number");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date_time");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_name");

                    b.Property<long?>("CreatedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("created_sid");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("credit_limit");

                    b.Property<int>("DisplayOrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("display_order_number");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("modified_name");

                    b.Property<long?>("ModifiedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_sid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("postal_code");

                    b.Property<byte>("SupplierTypeKubun")
                        .HasColumnType("tinyint")
                        .HasColumnName("supplier_type_kubun");

                    b.Property<DateTime>("TransactionStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_start_date");

                    b.Property<bool>("UseFlag")
                        .HasColumnType("bit")
                        .HasColumnName("use_flag");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Sid");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("m_supplier", (string)null);
                });

            modelBuilder.Entity("Takazono.Ojt.WebApi.Entities.Unit", b =>
                {
                    b.Property<long>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sid"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date_time");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_name");

                    b.Property<long?>("CreatedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("created_sid");

                    b.Property<int>("DisplayOrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("display_order_number");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("modified_name");

                    b.Property<long?>("ModifiedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_sid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<bool>("UnDeleteFlag")
                        .HasColumnType("bit")
                        .HasColumnName("un_delete_flag");

                    b.Property<bool>("UseFlag")
                        .HasColumnType("bit")
                        .HasColumnName("use_flag");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Sid");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("m_unit", (string)null);

                    b.HasData(
                        new
                        {
                            Sid = 1L,
                            Code = "EA",
                            CreatedDateTime = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedName = "seed",
                            DisplayOrderNumber = 1,
                            ModifiedDateTime = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedName = "seed",
                            Name = "個",
                            UnDeleteFlag = true,
                            UseFlag = true,
                            Version = new byte[0]
                        },
                        new
                        {
                            Sid = 2L,
                            Code = "BOX",
                            CreatedDateTime = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedName = "seed",
                            DisplayOrderNumber = 2,
                            ModifiedDateTime = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedName = "seed",
                            Name = "箱",
                            UnDeleteFlag = false,
                            UseFlag = true,
                            Version = new byte[0]
                        },
                        new
                        {
                            Sid = 3L,
                            Code = "CS",
                            CreatedDateTime = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedName = "seed",
                            DisplayOrderNumber = 3,
                            ModifiedDateTime = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedName = "seed",
                            Name = "ケース",
                            UnDeleteFlag = false,
                            UseFlag = true,
                            Version = new byte[0]
                        },
                        new
                        {
                            Sid = 4L,
                            Code = "SET",
                            CreatedDateTime = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedName = "seed",
                            DisplayOrderNumber = 4,
                            ModifiedDateTime = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedName = "seed",
                            Name = "セット",
                            UnDeleteFlag = false,
                            UseFlag = true,
                            Version = new byte[0]
                        });
                });

            modelBuilder.Entity("Takazono.Ojt.WebApi.Entities.User", b =>
                {
                    b.Property<long>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Sid"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date_time");

                    b.Property<string>("CreatedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_name");

                    b.Property<long?>("CreatedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("created_sid");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date_time");

                    b.Property<string>("ModifiedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("modified_name");

                    b.Property<long?>("ModifiedSid")
                        .HasColumnType("bigint")
                        .HasColumnName("modified_sid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password_hash");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<bool>("UseFlag")
                        .HasColumnType("bit")
                        .HasColumnName("use_flag");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_name");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("version");

                    b.HasKey("Sid");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("m_user", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
